import type { Metadata } from "next";
import "../shared/styles/globals.css";
import "../shared/styles/reset.css";
import Header from "@/widgets/header/ui/header";
import Providers from "@/shared/utils/providers";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="w-[85%] mx-auto bg-white dark:text-black">
        <Providers>
          <Header />
          {/* <div className="sm:pb-[100px] lg:pb-[120px]"> */}
          {children}
          {/* </div> */}
        </Providers>
      </body>
    </html>
  );
}
