import type { Metadata } from "next";
import "../shared/styles/globals.css";
import "../shared/styles/reset.css";
import Providers from "@/shared/utils/providers";
import { ToastContainer } from "react-toastify";
import Navigation from "@/widgets/navigation/ui/navigation";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="w-[85%] mx-auto pb-20 bg-white dark:text-black">
        <Providers>
          <Navigation>
            {children}
            <ToastContainer
              position="top-right"
              autoClose={1000}
              hideProgressBar={true}
              newestOnTop={false}
              limit={3}
              closeOnClick={true}
            />
          </Navigation>
        </Providers>
      </body>
    </html>
  );
}
